version: "2"
services:
  api:
    build: ./api
    links:
      - banco
    ports:
      - "5000:5000"

  banco:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./banco:/docker-entrypoint-initdb.d/:ro
